"""
FEATURE ENGINEERING MODULE
--------------------------
This module implements the deterministic calculation of explainable features.
These features are computed at runtime from cleaned data and are not persisted.
"""

import pandas as pd
import numpy as np

def compute_features(df):
    """
    Computes a fixed set of features for market analysis.
    
    Features:
    1. Volatility_20D: Rolling 20-day standard deviation of Daily returns.
    2. Drawdown_20D: (Close / 20-day Max Close) - 1.
    3. Trend_Strength_50D: (Close - 50-day SMA) / 50-day SMA.
    4. Volume_Anomaly_20D: (Volume - 20-day Mean Volume) / 20-day Std Volume.
    
    Args:
        df (pd.DataFrame): Cleaned OHLCV data with 'Daily_Return'.
        
    Returns:
        pd.DataFrame: DataFrame with added feature columns.
    """
    # Work on a copy to avoid side effects
    df = df.copy()
    
    # 1. Rolling Volatility (20D)
    # Using 'Daily_Return' calculated in data cleaning
    df['Volatility_20D'] = df['Daily_Return'].rolling(window=20).std()
    
    # 2. Rolling Drawdown (20D)
    # Drawdown from the 20-day rolling high
    rolling_max = df['Close'].rolling(window=20).max()
    df['Drawdown_20D'] = (df['Close'] / rolling_max) - 1.0
    
    # 3. Trend Strength (50D)
    # Normalized deviation from 50-day SMA
    sma_50 = df['Close'].rolling(window=50).mean()
    df['Trend_Strength_50D'] = (df['Close'] - sma_50) / sma_50
    
    # 4. Volume Anomaly (20D Z-Score)
    vol_mean_20 = df['Volume'].rolling(window=20).mean()
    vol_std_20 = df['Volume'].rolling(window=20).std()
    
    # Avoid division by zero
    df['Volume_Anomaly_20D'] = (df['Volume'] - vol_mean_20) / vol_std_20.replace(0, np.nan)
    
    # Drop NaN rows generated by rolling windows (requires at least 50 days)
    df = df.dropna()
    
    return df
